"""
Django settings for Main project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment-driven settings. In production, set DJANGO_SECRET_KEY,
# DJANGO_DEBUG=False and DJANGO_ALLOWED_HOSTS in the deployment environment.
# The fallbacks below only apply when those variables are unset, and are
# safe defaults for local development only.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-n)-ur$w5bcd(-=-gb=kxs#k#$=o2b+dciy=e)af*s*58830z62',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Fails safe: an unset DJANGO_DEBUG now means DEBUG=False (production
# posture) instead of DEBUG=True. Local development must explicitly set
# DJANGO_DEBUG=True — see .env.example.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

if not DEBUG:
    # Hardened cookie/transport posture for production. A reverse proxy
    # terminating TLS in front of this app must also forward
    # X-Forwarded-Proto, hence SECURE_PROXY_SSL_HEADER below.
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # Django's CSRF token must be readable by JS for AJAX submissions.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'simple_history',
    'django.contrib.humanize',
    
    ]

EXTERNAL_APPS = [
    'Authentication',
    'Dashboard',
    'Shift_Handover',
    'Bill_Master',
    'Company',
    'Expense',    
    'Reports',
    'Revenue',
    'Staff_Profile',    
]

INSTALLED_APPS = EXTERNAL_APPS + INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files directly from the WSGI process (with
    # compression + far-future cache headers) so a deployment doesn't need
    # a separate nginx/CDN static-file config to go live. Must sit right
    # after SecurityMiddleware, before everything else.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'Authentication.middleware.AutoLogoutMiddleware',
    # External Middleware
    'Authentication.middleware.SuperAdminOnlyMiddleware',

]

ROOT_URLCONF = 'Main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Main.context_processors.hotel_pallav_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'Main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# Defaults to SQLite for local development. SQLite serializes writes at the
# file level and is not safe for a multi-worker production deployment with
# concurrent bill/advance writes — and on a serverless platform (Vercel and
# similar) the filesystem is ephemeral, so SQLite cannot be used there at
# all, not just "not recommended". Two ways to point at a real database in
# production, checked in this order:
#
# 1. DATABASE_URL — a single connection-string env var, e.g.
#    postgres://user:pass@host:5432/dbname?sslmode=require. This is what
#    Vercel (and Heroku/Render) automatically set when you attach a
#    Postgres integration (Vercel Postgres, Neon, Supabase, etc.) — no
#    manual configuration needed beyond attaching the integration.
# 2. DJANGO_DB_ENGINE (e.g. 'django.db.backends.postgresql') plus
#    DJANGO_DB_NAME/DJANGO_DB_USER/DJANGO_DB_PASSWORD/DJANGO_DB_HOST/DJANGO_DB_PORT
#    — for hosts that hand you discrete credentials instead of one URL.

if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '60')),
            ssl_require=os.environ.get('DJANGO_DB_SSL_REQUIRE', 'True') == 'True',
        )
    }
elif os.environ.get('DJANGO_DB_ENGINE'):
    DATABASES = {
        'default': {
            'ENGINE': os.environ['DJANGO_DB_ENGINE'],
            'NAME': os.environ.get('DJANGO_DB_NAME', 'hotel_pallav'),
            'USER': os.environ.get('DJANGO_DB_USER', ''),
            'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
            'HOST': os.environ.get('DJANGO_DB_HOST', ''),
            'PORT': os.environ.get('DJANGO_DB_PORT', ''),
            'CONN_MAX_AGE': int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # Give concurrent requests time to wait for the write lock
            # instead of raising "database is locked" immediately.
            'OPTIONS': {'timeout': 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-in'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# User-uploaded media — kept out of STATIC_ROOT/STATICFILES_DIRS on purpose,
# collectstatic must never sweep guest documents into the static bundle.
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Optional S3-compatible object storage for MEDIA (staff photos, resumes,
# invoice scans). Off by default — files are written to MEDIA_ROOT on local
# disk, which is fine for a single persistent server but is LOST on every
# deploy/restart on an ephemeral filesystem (most PaaS/containers). Set
# DJANGO_USE_S3=True plus the AWS_* variables below to switch to a bucket;
# requires an actual bucket to be provisioned first (deployment-time
# decision, not something this codebase can do on its own).
if os.environ.get('DJANGO_USE_S3', 'False') == 'True':
    INSTALLED_APPS.append('storages')
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', '')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '') or None
    AWS_DEFAULT_ACL = None  # bucket policy controls access, not per-object ACLs
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/' if AWS_S3_CUSTOM_DOMAIN else f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'


# Logging
# https://docs.djangoproject.com/en/5.0/topics/logging/
#
# Every app logger below writes through the app's own name (e.g.
# logging.getLogger(__name__) inside Bill_Master/views.py resolves to the
# 'Bill_Master' logger via propagation), so failures are attributable to a
# specific module instead of vanishing into stdout via bare print(e) calls.

LOG_DIR = BASE_DIR / 'logs'

# Probe for a writable filesystem instead of assuming one. On a serverless
# host (Vercel and similar) everything outside /tmp is read-only, so
# LOG_DIR.mkdir() — and RotatingFileHandler trying to open a file under it —
# would raise on every single cold start, crashing the whole app before it
# could handle a request (confirmed root cause of a FUNCTION_INVOCATION_FAILED
# crash on Vercel: this used to run unconditionally). Console-only logging is
# also the *correct* approach there, not just a fallback — Vercel (and most
# serverless/container platforms) captures stdout/stderr automatically and
# shows it in their own log viewer.
try:
    LOG_DIR.mkdir(exist_ok=True)
    _probe = LOG_DIR / '.write_test'
    _probe.write_text('')
    _probe.unlink()
    _LOGS_WRITABLE = True
except OSError:
    _LOGS_WRITABLE = False

_log_handlers = ['console'] + (['app_file', 'error_file'] if _LOGS_WRITABLE else [])
_error_log_handlers = ['console'] + (['error_file'] if _LOGS_WRITABLE else [])

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {module}.{funcName}:{lineno} — {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple' if DEBUG else 'verbose',
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
        **({
            'app_file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': LOG_DIR / 'app.log',
                'maxBytes': 10 * 1024 * 1024,  # 10 MB
                'backupCount': 5,
                'formatter': 'verbose',
                'level': 'INFO',
            },
            'error_file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': LOG_DIR / 'error.log',
                'maxBytes': 10 * 1024 * 1024,
                'backupCount': 10,
                'formatter': 'verbose',
                'level': 'ERROR',
            },
        } if _LOGS_WRITABLE else {}),
    },
    'root': {
        'handlers': _log_handlers,
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': _log_handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': _error_log_handlers,
            'level': 'ERROR',
            'propagate': False,
        },
        # One logger per app so a grep of logs/app.log or logs/error.log
        # for "Bill_Master" (etc.) isolates that app's activity — when the
        # filesystem is writable. On a read-only host, console (captured by
        # the platform's own log viewer) is the only handler anyway.
        **{
            app_name: {
                'handlers': _log_handlers,
                'level': 'INFO',
                'propagate': False,
            }
            for app_name in EXTERNAL_APPS
        },
    },
}