# Generated by Django 5.0.4 on 2024-10-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0002_alter_food_cash_deposite_deposite_food_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_cash_deposite',
            name='Deposite_Hotel_Amount_In_Words',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
