# Generated by Django 5.0.4 on 2024-10-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revenue', '0003_hotel_cash_deposite_deposite_hotel_amount_in_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_cash_deposite',
            name='Deposite_Food_Amount_In_Words',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
