# Generated by Django 5.1.5 on 2026-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Revenue", "0006_normalize_amount_text_before_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_cash_deposite",
            name="Deposite_Food_Amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="hotel_cash_deposite",
            name="Deposite_Hotel_Amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
