# Generated by Django 4.1.13 on 2024-04-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff_Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Cash_Miscellaneous_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Miscellaneous_Expenses_Food_Date', models.DateField()),
                ('Miscellaneous_Expenses_Food_Time', models.TimeField()),
                ('Miscellaneous_Expenses_Food_Username', models.CharField(max_length=100)),
                ('Miscellaneous_Expenses_Food_Expense_Name', models.CharField(max_length=100)),
                ('Miscellaneous_Expenses_Food_Amount', models.CharField(max_length=50)),
                ('Miscellaneous_Expenses_Food_Instruction', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Cash_Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Withdrawal_Food_Date', models.DateField()),
                ('Withdrawal_Food_Time', models.TimeField()),
                ('Withdrawal_Food_Username', models.CharField(max_length=100)),
                ('Withdrawal_Food_Withdrawer', models.CharField(max_length=100)),
                ('Withdrawal_Food_Amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Cash_Miscellaneous_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Miscellaneous_Expenses_Hotel_Date', models.DateField()),
                ('Miscellaneous_Expenses_Hotel_Time', models.TimeField()),
                ('Miscellaneous_Expenses_Hotel_Username', models.CharField(max_length=100)),
                ('Miscellaneous_Expenses_Hotel_Expense_Name', models.CharField(max_length=100)),
                ('Miscellaneous_Expenses_Hotel_Amount', models.CharField(max_length=50)),
                ('Miscellaneous_Expenses_Hotel_Instruction', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Cash_Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Withdrawal_Hotel_Date', models.DateField()),
                ('Withdrawal_Hotel_Time', models.TimeField()),
                ('Withdrawal_Hotel_Username', models.CharField(max_length=100)),
                ('Withdrawal_Hotel_Withdrawer', models.CharField(max_length=100)),
                ('Withdrawal_Hotel_Amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Advance_date', models.DateField()),
                ('Staff_Advance_time', models.TimeField()),
                ('Staff_Advance_username', models.CharField(max_length=100)),
                ('Staff_Advance_year_month', models.CharField(max_length=7)),
                ('Staff_Advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Staff_Advance_instruction', models.TextField(blank=True)),
                ('Staff_Advance_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff_Profile.user_profile')),
            ],
        ),
    ]
