# Generated by Django 5.0.4 on 2024-09-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_food_cash_miscellaneous_expenses_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_cash_miscellaneous_expenses',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='food_cash_withdrawal',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='hotel_cash_miscellaneous_expenses',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='hotel_cash_withdrawal',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='staff_advance',
            name='Username',
        ),
        migrations.AlterField(
            model_name='food_cash_miscellaneous_expenses',
            name='Miscellaneous_Expenses_Food_Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food_cash_withdrawal',
            name='Withdrawal_Food_Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel_cash_miscellaneous_expenses',
            name='Miscellaneous_Expenses_Hotel_Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel_cash_withdrawal',
            name='Withdrawal_Hotel_Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff_advance',
            name='Staff_Advance_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
