# Generated by Django 5.0.4 on 2024-10-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0003_remove_food_cash_miscellaneous_expenses_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_advance',
            name='Staff_Advance_Amount_In_Words',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
