# Generated by Django 5.0.4 on 2024-10-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0004_staff_advance_staff_advance_amount_in_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_cash_miscellaneous_expenses',
            name='Miscellaneous_Expenses_Food_Amount_In_Words',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_cash_withdrawal',
            name='Withdrawal_Food_Amount_In_Words',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_cash_miscellaneous_expenses',
            name='Miscellaneous_Expenses_Hotel_Amount_In_Words',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_cash_withdrawal',
            name='Withdrawal_Hotel_Amount_In_Words',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
