# Generated by Django 5.0.4 on 2024-10-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0005_food_cash_miscellaneous_expenses_miscellaneous_expenses_food_amount_in_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_cash_miscellaneous_expenses',
            name='Miscellaneous_Expenses_Full_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='food_cash_withdrawal',
            name='Withdrawal_Food_Full_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel_cash_miscellaneous_expenses',
            name='Miscellaneous_Expenses_Full_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel_cash_withdrawal',
            name='Withdrawal_Hotel_Full_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff_advance',
            name='Staff_Advance_Full_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
