# Generated by Django 5.0.4 on 2024-10-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0006_food_cash_miscellaneous_expenses_miscellaneous_expenses_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_cash_miscellaneous_expenses',
            old_name='Miscellaneous_Expenses_Full_Name',
            new_name='Miscellaneous_Expenses_Food_Full_Name',
        ),
        migrations.RenameField(
            model_name='hotel_cash_miscellaneous_expenses',
            old_name='Miscellaneous_Expenses_Full_Name',
            new_name='Miscellaneous_Expenses_Hotel_Full_Name',
        ),
    ]
