# Generated by Django 5.1.5 on 2026-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Expense", "0008_normalize_amount_text_before_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_cash_miscellaneous_expenses",
            name="Miscellaneous_Expenses_Food_Amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="food_cash_withdrawal",
            name="Withdrawal_Food_Amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="hotel_cash_miscellaneous_expenses",
            name="Miscellaneous_Expenses_Hotel_Amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="hotel_cash_withdrawal",
            name="Withdrawal_Hotel_Amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
