# Generated by Django 5.1.5 on 2026-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_authentication_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
