# Generated by Django 4.1.13 on 2024-04-17 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100, unique=True)),
                ('Company_Address', models.CharField(max_length=100, null=True)),
                ('Company_Email', models.EmailField(max_length=254, null=True)),
                ('Company_Country', models.CharField(max_length=100, null=True)),
                ('Company_Pincode', models.CharField(max_length=20, null=True)),
                ('Company_Nationality', models.CharField(max_length=100, null=True)),
                ('Company_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Company_Phone_Number', models.CharField(max_length=15, null=True)),
                ('Company_Discount_Percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Company_Instruction', models.TextField(null=True)),
                ('Company_GST_Number', models.CharField(max_length=50, null=True)),
                ('Company_GST_Percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Company_TCS_Percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Company_TDS_Percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Company_MD_One_Name', models.CharField(max_length=100, null=True)),
                ('Company_MD_One_Email', models.EmailField(max_length=254, null=True)),
                ('Company_MD_One_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Company_MD_Second_Name', models.CharField(max_length=100, null=True)),
                ('Company_MD_Second_Email', models.EmailField(max_length=254, null=True)),
                ('Company_MD_Second_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Company_HR_Head_Name', models.CharField(max_length=100, null=True)),
                ('Company_HR_Head_Email', models.EmailField(max_length=254, null=True)),
                ('Company_HR_Head_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Company_Assitant_HR_Name', models.CharField(max_length=100, null=True)),
                ('Company_Assitant_HR_Email', models.EmailField(max_length=254, null=True)),
                ('Company_Assitant_HR_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Company_Accountant_Head_Name', models.CharField(max_length=100, null=True)),
                ('Company_Accountant_Head_Email', models.EmailField(max_length=254, null=True)),
                ('Company_Accountant_Head_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Company_Accountant_Assistant_One_Name', models.CharField(max_length=100, null=True)),
                ('Company_Accountant_Assistant_One_Email', models.EmailField(max_length=254, null=True)),
                ('Company_Accountant_Assistant_One_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Company_Accountant_Assistant_Two_Name', models.CharField(max_length=100, null=True)),
                ('Company_Accountant_Assistant_Two_Email', models.EmailField(max_length=254, null=True)),
                ('Company_Accountant_Assistant_Two_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_profiles', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_company_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
