# Generated by Django 5.0.4 on 2024-10-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_company_profile_company_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='Company_GST_Number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='Company_Name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='company_profile',
            unique_together={('Company_Name', 'Company_GST_Number')},
        ),
    ]
