# Generated by Django 5.0.4 on 2024-10-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_company_profile_company_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company_profile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='Company_GST_Number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='Company_Name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
