# Generated by Django 5.1.5 on 2026-08-24 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0004_alter_company_profile_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company_profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("Company_GST_Number", ""), _negated=True),
                    ("Company_GST_Number__isnull", False),
                ),
                fields=("Company_GST_Number",),
                name="unique_company_gst_number_when_set",
            ),
        ),
    ]
