# Generated by Django 5.0.4 on 2024-04-25 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Master_ADD_Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advance_Receipt_Number', models.CharField(max_length=100, null=True, unique=True)),
                ('Advance_Guest_Name', models.CharField(max_length=255, null=True)),
                ('Advance_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Advance_Payment_Date', models.DateField(null=True)),
                ('Hotel_Advance_Amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Food_Advance_Amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Hotel_Advance_MOD', models.CharField(max_length=20, null=True)),
                ('Food_Advance_MOD', models.CharField(max_length=20, null=True)),
                ('Advance_Reference_Name', models.CharField(max_length=255, null=True)),
                ('Advance_Reference_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Advance_Instruction', models.CharField(max_length=255, null=True)),
                ('Hotel_Balance_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True)),
                ('Food_Balance_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True)),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True)),
                ('Hotel_Refund_Advance_Amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Food_Refund_Advance_Amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Hotel_Refund_MOD', models.CharField(max_length=20, null=True)),
                ('Food_Refund_MOD', models.CharField(max_length=20, null=True)),
                ('Refund_Payment_Date', models.DateField(null=True)),
                ('Refund_Guest_Name', models.CharField(max_length=255, null=True)),
                ('Refund_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Refund_Instruction', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Master_ADD_Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_Master_Bill_Number', models.CharField(max_length=100, null=True, unique=True)),
                ('Bill_Master_Bill_Date', models.DateField(null=True)),
                ('Bill_Master_Guest_Name', models.CharField(max_length=255, null=True)),
                ('Bill_Master_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('Bill_Master_Hotel_Plan', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Master_Hotel_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Hotel_Plan_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Hotel_Laundry_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Hotel_GST', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Hotel_Mode_Of_Payment', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Master_Food_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Food_Plan_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Food_Laundry_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Food_GST', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Food_Mode_Of_Payment', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Master_Total_Hotel_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Total_Food_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Reference_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Master_Reference_Mobile_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Bill_Master_Instruction', models.TextField(blank=True, null=True)),
                ('Bill_Master_Balance_Hotel_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Balance_Food_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Advance_Delete_Hotel_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Advance_Delete_Food_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Debit_BIll_PDF', models.FileField(null=True, upload_to='Invoice_Debit_Bill/')),
                ('Bill_Master_Debit_Bill_Date', models.DateField(null=True)),
                ('Bill_Master_Debit_Hotel_Mode_Of_Payment', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Master_Debit_Food_Mode_Of_Payment', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Master_Debit_Hotel_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Debit_Food_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('Bill_Master_Debit_Reference_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Master_Debit_Reference_Mobile_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Bill_Master_Debit_Instruction', models.TextField(blank=True, null=True)),
                ('Bill_Master_Advance_Date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_bills_advance_date', to='Bill_Master.bill_master_add_advance')),
                ('Bill_Master_Advance_Guest_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_bills_guest_name', to='Bill_Master.bill_master_add_advance')),
                ('Bill_Master_Advance_Receipt_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_bills_receipt', to='Bill_Master.bill_master_add_advance')),
                ('Bill_Master_Bill_Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company_profile')),
                ('Bill_Master_Food_Advance_Amounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_bills_food_advance', to='Bill_Master.bill_master_add_advance')),
                ('Bill_Master_Hotel_Advance_Amounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_bills_hotel_advance', to='Bill_Master.bill_master_add_advance')),
            ],
        ),
    ]
