# Generated by Django 5.0.4 on 2024-04-25 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_advance',
            name='Bill_Master_Bill_Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company_profile'),
        ),
    ]
