# Generated by Django 5.0.4 on 2024-04-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0002_bill_master_add_advance_bill_master_bill_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_master_add_advance',
            old_name='Bill_Master_Bill_Company',
            new_name='Advance_Bill_Company',
        ),
    ]
