# Generated by Django 5.0.4 on 2024-04-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0003_rename_bill_master_bill_company_bill_master_add_advance_advance_bill_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Advance_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Advance_Guest_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Advance_Receipt_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Food_Advance_Amounts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Hotel_Advance_Amounts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
