# Generated by Django 5.0.4 on 2024-04-29 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0004_alter_bill_master_add_bill_bill_master_advance_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_master_add_bill',
            old_name='Bill_Master_Food_Laundry_Amount',
            new_name='Bill_Master_Laundry_Amount',
        ),
        migrations.RenameField(
            model_name='bill_master_add_bill',
            old_name='Bill_Master_Food_Plan_Amount',
            new_name='Bill_Master_Plan_Amount',
        ),
        migrations.RemoveField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Hotel_Laundry_Amount',
        ),
        migrations.RemoveField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Hotel_Plan_Amount',
        ),
    ]
