# Generated by Django 5.0.4 on 2024-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0005_rename_bill_master_food_laundry_amount_bill_master_add_bill_bill_master_laundry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Advance_Company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
