# Generated by Django 5.0.4 on 2024-05-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0006_bill_master_add_bill_bill_master_advance_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_master_add_bill',
            old_name='Bill_Master_Laundry_Amount',
            new_name='Bill_Master_Food_Laundry_Amount',
        ),
        migrations.RenameField(
            model_name='bill_master_add_bill',
            old_name='Bill_Master_Plan_Amount',
            new_name='Bill_Master_Food_Plan_Amount',
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Hotel_Laundry_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Hotel_Plan_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
