# Generated by Django 5.0.4 on 2024-06-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0007_rename_bill_master_laundry_amount_bill_master_add_bill_bill_master_food_laundry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Advance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Advance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
