# Generated by Django 5.0.4 on 2024-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0008_bill_master_add_bill_bill_master_debit_food_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Bill_Date_1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Bill_Date_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Bill_Date_3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Bill_Date_4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Bill_Date_5',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Amount_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Amount_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Amount_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Amount_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Amount_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Mode_Of_Payment_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Mode_Of_Payment_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Mode_Of_Payment_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Mode_Of_Payment_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Food_Mode_Of_Payment_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Amount_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Amount_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Amount_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Amount_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Amount_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Mode_Of_Payment_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Mode_Of_Payment_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Mode_Of_Payment_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Mode_Of_Payment_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Debit_Hotel_Mode_Of_Payment_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
