# Generated by Django 5.0.4 on 2024-09-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0010_remove_bill_master_add_bill_bill_master_debit_bill_date_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Formatted_Advance_Receipt_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
