# Generated by Django 5.0.4 on 2024-09-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0011_bill_master_add_bill_formatted_advance_receipt_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_master_add_bill',
            old_name='Formatted_Advance_Receipt_Number',
            new_name='Bill_Master_Formated_Advance_Receipt_Number',
        ),
    ]
