# Generated by Django 5.0.4 on 2024-09-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0012_rename_formatted_advance_receipt_number_bill_master_add_bill_bill_master_formated_advance_receipt_nu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_advance',
            name='Excessive_Unique_Advance_Receipt_Number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Formated_Advance_Receipt_Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
