# Generated by Django 5.0.4 on 2024-09-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0013_bill_master_add_advance_excessive_unique_advance_receipt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_master_add_advance',
            name='Excessive_Unique_Advance_Receipt_Number',
        ),
    ]
