# Generated by Django 5.0.4 on 2024-10-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0014_remove_bill_master_add_advance_excessive_unique_advance_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Advance_Hotel_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
