# Generated by Django 5.0.4 on 2024-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill_Master', '0015_bill_master_add_bill_bill_master_advance_hotel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_master_add_bill',
            name='Bill_Master_Advance_Food_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
