# Generated by Django 4.1.13 on 2024-04-17 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Full_Name', models.CharField(max_length=100, null=True)),
                ('User_Address', models.CharField(max_length=100, null=True)),
                ('User_Mobile_Number', models.CharField(max_length=15, null=True)),
                ('User_Date_Of_Birth', models.DateField(null=True)),
                ('User_Email_ID', models.EmailField(max_length=254, null=True)),
                ('User_Nationality', models.CharField(max_length=100, null=True)),
                ('User_Country_And_Pin_Code', models.CharField(max_length=100, null=True)),
                ('User_Gender', models.CharField(max_length=10, null=True)),
                ('User_Job_Title', models.CharField(max_length=100, null=True)),
                ('User_Department', models.CharField(max_length=100, null=True)),
                ('User_Qualification', models.CharField(max_length=100, null=True)),
                ('User_Qualification_Institution', models.CharField(max_length=100, null=True)),
                ('User_Skills', models.TextField(null=True)),
                ('User_Salary', models.IntegerField(null=True)),
                ('User_Image', models.ImageField(null=True, upload_to='user_images/')),
                ('User_Document_Frontside_Image', models.ImageField(null=True, upload_to='user_documents/')),
                ('User_Document_Backside_Image', models.ImageField(null=True, upload_to='user_documents/')),
                ('User_Resume_PDF', models.FileField(null=True, upload_to='user_resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(editable=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_profiles', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_user_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
