# Generated by Django 5.0.4 on 2024-06-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
