# Generated by Django 5.0.4 on 2024-06-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Profile', '0002_user_profile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='active',
        ),
    ]
