# Generated by Django 5.0.4 on 2024-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Profile', '0003_remove_user_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
