# Generated by Django 5.0.4 on 2024-10-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Profile', '0004_user_profile_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='paused',
            new_name='User_Paused',
        ),
    ]
