# Generated by Django 5.0.4 on 2024-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_Profile', '0005_rename_paused_user_profile_user_paused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='User_Paused',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
