# Generated by Django 5.0.4 on 2024-06-30 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Username', models.CharField(max_length=100, null=True)),
                ('Shift', models.CharField(max_length=20, null=True)),
                ('message_One', models.TextField(null=True)),
                ('message_Two', models.TextField(null=True)),
                ('message_Three', models.TextField(null=True)),
                ('message_Four', models.TextField(null=True)),
                ('message_Five', models.TextField(null=True)),
                ('Special_Instruction', models.TextField(null=True)),
                ('Notes_Count', models.CharField(default='0', max_length=10, null=True)),
                ('Two_Thousand_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Five_Hundred_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Two_Hundred_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('One_Hundred_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Fifty_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Twenty_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Ten_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Five_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Coins_Counts', models.CharField(default='0', max_length=10, null=True)),
                ('Two_Thousand_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Five_Hundred_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Two_Hundred_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('One_Hundred_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Fifty_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Twenty_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Ten_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Five_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Coins_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
        ),
    ]
