# Generated by Django 5.0.4 on 2024-06-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shift_Handover', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_handover',
            name='created_at',
        ),
    ]
