# Generated by Django 5.0.4 on 2024-09-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shift_Handover', '0002_remove_shift_handover_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_handover',
            name='Two_Thousand_Counts',
        ),
        migrations.RemoveField(
            model_name='shift_handover',
            name='Two_Thousand_Total',
        ),
    ]
