# Generated by Django 5.0.4 on 2024-10-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shift_Handover', '0005_alter_shift_handover_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_handover',
            name='Update_Count',
        ),
    ]
