# Generated by Django 5.0.4 on 2024-10-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shift_Handover', '0007_rename_coins_counts_shift_handover_shift_handover_coins_counts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift_handover',
            old_name='Date',
            new_name='Shift_Handover_Date',
        ),
        migrations.RenameField(
            model_name='shift_handover',
            old_name='Time',
            new_name='Shift_Handover_Time',
        ),
    ]
