# Generated by Django 5.0.4 on 2024-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shift_Handover', '0008_rename_date_shift_handover_shift_handover_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_handover',
            name='Shift_Handover_Full_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
